### ISSUE TITLE
View - customize layout with hidden relations

### ISSUE THREAD

**Issue by vitalegi** [vitalegi/archi#12]
I want to be able to define a list of rules where each rule has the list of IDs of elements to be put in a hidden relation.

- [x] if any of the 2 element is not present in the view, ignore the rule
- [x] Add hidden relations, for each diagram
- [x] Add hidden relations, globally

e.g.:

## Globally

```
options:
  relations:
    - type: hidden
      elements:
        - A
        - B
        - C  
view:
  ...
```

## On a diagram

```
view:
  ...
  options:
    relations:
      - type: hidden
        elements:
          - A
          - B
          - C
```

causes:

```
A-[hidden]->B
B-[hidden]->C
```
