### ISSUE TITLE
Dynamic flows - aggregate info

### ISSUE THREAD

**Issue by vitalegi** [vitalegi/archi#34]
As a user I want to be able to define several steps that build up a flow so that:

- [x] each flow has an id
- [x] relations declared in a flow are available in diagrams

proposed structure:

```
elements:
  ...
relations:
  ...
diagrams:
  ...
flows:
  - id: xxx
    steps:
      - from: xxx
        to: yyy
        description: lorem ipsum
        label: ...
        link: ...
        technologies: ...
```
