### ISSUE TITLE
Excel export: list of software systems

### ISSUE THREAD

**Issue by vitalegi** [vitalegi/archi#63]
As a user I want to configure an export such that:

```
- type: EXCEL
  id: id of the export
  sheets:
  - type: SOFTWARE_SYSTEMS
    name: name of the sheet
    columns:
    - ...
```

Where each value of columns can be one of:

- id
- name
- description
- tags
- technologies
- properties.key_x: value of property[key_x], if exist

Expected outcome is an excel file with name id.xlsx, with a sheet `sheets[0].name`, with the list of all software systems.
